### PR TITLE
Connect to pretalx

### PR DESCRIPTION
**Pull request by rixx**
This PR adds a "connected" field to the pretalx information, to be used in connection with the pretalx-venueless plugin
for pretalx.

Workflow when entering pretalx information:

- The frontend uses the URL at `{domain}/{event}/p/venueless/check` to check if the pretalx-venueless plugin is 
  active for the given event. A 200 response is positive, anything else (404 or CSRF error, for example) negative.
- If the check is negative, the frontend asks the user to first activate the pretalx-venueless plugin on the plugin
  page at `{domain}/orga/event/{event}/settings/plugins`, and to retry afterwards
- Once the check is positive, the frontend shows a "Connect to (with?) pretalx" button. Clicking the button opens a new
  tab for `{domain}/orga/event/{event}/settings/p/venueless?url={api_url}&token={token}&returnUrl={url}`. The `api_url` should contain
  the base API url, so `{veneueless_domain}/api/worlds/{world_id}/`, the `token` has to be a token with `world:api` capabilities.
- pretalx will display a confirmation dialogue with the provided information. Upon confirmation, pretalx will
  (synchronously) execute one request against the schedule update API, which will switch the "confirmed" flag to True.
  Notably, this does *not* trigger a world update push, since no important data is changed, so to display this change,
  the API would need to poll. I don't really see a great alternative to that atm.

Open questions:

- @raphaelm, are we fine giving out `world:api` tokens here, or should we add a more restricted scope just for schedule updates?
- Does the frontend have a way of getting a full token, not just a short token?

### CODE REVIEW

**Comment by rixx** [comment]
@rashfael To make it easier to point people to the right location to start this process on the venueless side, maybe we could move the schedule config to its own page in the configuration side bar? The "load schedule" button is a bit odd at the moment.

In any case, if the location of the schedule config changes with this PR, please let me know so I can adjust the instructions on the pretalx end of things.

**Comment by rashfael** [comment]
Instead of opening a new tab, we could also directly redirect to pretalx in the same tab and add a returnUrl query param to send people back to after pretalx has finished setting up.

**Comment by rashfael** [comment]
> @rashfael To make it easier to point people to the right location to start this process on the venueless side, maybe we could move the schedule config to its own page in the configuration side bar? The "load schedule" button is a bit odd at the moment.
Yeah, that's a good idea.

**Comment by rixx** [comment]
> Instead of opening a new tab, we could also directly redirect to pretalx in the same tab and add a returnUrl query param to send people back to after pretalx has finished setting up.

+1, updated the post above

**Comment by rixx** [comment]
The pretalx plugin lives [here](https://github.com/pretalx/pretalx-venueless) and is release-ready. I've installed it on pretalx.com, so you can try it out with your test event (I think you, rash,  have access to your own event and 35c3, but lmk if you want others).

**Comment by raphaelm** [comment]
> @raphaelm, are we fine giving out world:api tokens here, or should we add a more restricted scope just for schedule updates?

I'd be fine with granting the permission for now since there's only so much you can do via the API, but I'd prefer if we use a specialized **trait** that is then granted world:api permission, so we can, if we later want, restrict the permission more tightly even for already created tokens.

> Does the frontend have a way of getting a full token, not just a short token?

No, we'd need to add that

**Comment by rixx** [comment]
@ both of you, I added a default trait called "schedule-update" that grants exactly just "world:api" permissions (on new events, of course). Hope I didn't overlook anything, I'm never quite sure which places to touch when changing permissions.

I added an optional `long` flag for the token generator endpoint, defaulting to `false`, so you should be able to request a token with the trait "schedule-update" and `long: true` @rashfael

**Comment by rashfael** [comment]
Currently you can also write `conftool: true` into `config.pretalx` via here https://github.com/venueless/venueless/blob/37e4d0d82c35a716fd121dccd1899fb7eda879d8/webapp/src/views/admin/config/SchedulePrompt.vue#L109

This does not seem to get saved anymore in this PR.

**Comment by rashfael** [comment]
The `long` token generator works, now I'm just getting a CORS error for the prexalx `/p/venueless/check` url even when it returns 200.

**Comment by rixx** [comment]
CORS should be fixed!

**Comment by rixx** [comment]
> Currently you can also write `conftool: true` into `config.pretalx` via here
> 
> https://github.com/venueless/venueless/blob/37e4d0d82c35a716fd121dccd1899fb7eda879d8/webapp/src/views/admin/config/SchedulePrompt.vue#L109
> 
> This does not seem to get saved anymore in this PR.

Should be fixed.

**Comment by rixx** [comment]
I also made the API strict, it now refuses any updates from pretalx that are not for the configured connection.

**Review by rixx — COMMENTED** [review]
wooo

**Pull request merged**
