### PR TITLE
Add a consent blocker for iframe content

### PR DESCRIPTION
**Pull request by rashfael**
As discussed in https://github.com/venueless/venueless/issues/345

## Todos
- [ ] "Remember my choice" actually working
- [ ] admin interface to enable blocker and add links to privacy policies
- [ ] i18n

### CODE REVIEW

**Comment by rashfael** [comment]
I finished the UI prototype and have a few decisions to make:
- Should we enable the blocker for ALL domains, regardless of if they have a link configured (and add a default link), or only enable the blocker for configured domains?
- Should the "policy link" label text (separate from href) be configurable PER domain or is globally per translation/text override enough?

Opinions @raphaelm @saschafoerster ?

Once we decided, I'll need someone to add the relevant config options on the backend side.

**Comment by raphaelm** [comment]
> Should we enable the blocker for ALL domains, regardless of if they have a link configured (and add a default link), or only enable the blocker for configured domains?

This is tough.

If we **do** enable it for all domains, organizers can feel safe that they did not miss anything. This generally sounds like a good idea. On the other hand, we then need a way to explicitly turn it **off** for domains where we know it is not required, or e.g. if the domain has their own consent management. I think that would be the best option, on by default, and option to turn off per domain.

> Should the "policy link" label text (separate from href) be configurable PER domain or is globally per translation/text override enough?

Globally is enough.

**Comment by saschafoerster** [comment]
> * Should we enable the blocker for ALL domains, regardless of if they have a link configured (and add a default link), or only enable the blocker for configured domains?

I would like to have an option to activate iFrame-Privacy-blocking for a whole venueless instance as you showed it in the picture. In general iFrames are just allowed, but if I want more privacy I turn this button on and all iFrames are blocked. If there are problems, I can turn it off and debug better and see, is it a problem of the website or a problem with the privacy-iframe-blocker. 

> * Should the "policy link" label text (separate from href) be configurable PER domain or is globally per translation/text override enough?

I would prefer to link to the responding policy link of the domains itself, as they don't need to be actualized and I don't need to create a separate page, where they are all linked. Maybe the chances are higher of people reading what happens with their data, when they are reading it directly instead of getting to a page of links, where they need to click a second time to get to the real terms. 

I would like to have one wildcard-field with the link to the general policy link, which is used, when I didn't use the link field of a certain domain. And this wildcard-field should also be shown somewhere in the venueless UI all the time. (you know, Impressum/contact and data privacy/Datenschutz are the two links, that need at least to be reachably from everywhere with one click).

**Comment by rashfael** [comment]
> I would like to have an option to activate iFrame-Privacy-blocking for a whole venueless instance as you showed it in the picture. In general iFrames are just allowed, but if I want more privacy I turn this button on and all iFrames are blocked. If there are problems, I can turn it off and debug better and see, is it a problem of the website or a problem with the privacy-iframe-blocker.

As @raphaelm noted, the interesting case is disabling/enabling iframe blockers per domain, even if we have a global default.

> I would prefer to link to the responding policy link of the domains itself, as they don't need to be actualized and I don't need to create a separate page, where they are all linked. Maybe the chances are higher of people reading what happens with their data, when they are reading it directly instead of getting to a page of links, where they need to click a second time to get to the real terms.

My question was specifically for the link **label**, not the link itself.

**Comment by rashfael** [comment]
This is what a data model could look like:

```js
iframe_blockers: {
  ['default' | domain]: {
    enabled: Boolean,
    policy_url: URL
  }
}
```
A `iframe_blocker` dict with the domain name or `default` as key and `{enabled, policy_url}` as values. This would even allow for a "disable by default, enable for these domains" use case.

Logic for deciding would be something like

```js
const blockerSettings = world.iframe_blockers[domain] || world.iframe_blockers.default
if (blockerSettings.enabled) {
  render(blockerSettings.policy_url)
}
```

Alternatively, we can also do a more classic approach with `iframe_blocker_default_enabled` , `iframe_blocker_default_policy_link` and a list of `iframe_blocker_domains`.

**Comment by rixx** [comment]
Added a section to `world.config` called `iframe_blocker` that defaults to `{default: {enabled: false, policy_url: null}}` – is that the default we want?

`world.config.iframe_blocker` can be written to, but content is currently not validated – do we need validation there?

**Comment by rashfael** [comment]
> `world.config.iframe_blocker` can be written to, but content is currently not validated – do we need validation there?

Probably not, since that is a pretty complex dict and probably not worth it.

**Pull request merged**
