### PR TITLE
Allow to limit the concurrent connections of one user

### PR DESCRIPTION
**Pull request by raphaelm**

### CODE REVIEW

**Comment by rashfael** [comment]
I don't think doing this with just an error and no interaction right now is a great idea. A limit of 2 is also rather low.

PWAs for example don't have a way to let the user reload the "page" manually, so you're stuck.
If connections per user are concern, we'd also should mux connections through a SharedWorker with such a low limit, but that also needs work in the protocol.

**Comment by raphaelm** [comment]
> I don't think doing this with just an error and no interaction right now is a great idea. A limit of 2 is also rather low.

The limit is configurable, I woul set it to unlimited by default, just turn it down to one or two for customers who fear lots of people would send the link around and watch the stream for free.

> PWAs for example don't have a way to let the user reload the "page" manually, so you're stuck.

Okay, so we need a button there?

> If connections per user are concern, we'd also should mux connections through a SharedWorker with such a low limit, but that also needs work in the protocol.

It's more like browsers per user, yes. Do you have other ideas how to approach this?

**Comment by rashfael** [comment]
> The limit is configurable, I woul set it to unlimited by default, just turn it down to one or two for customers who fear lots of people would send the link around and watch the stream for free.
Ah, okay. My gut tells me that a limit of one seems prone to race conditions (old connection must be guaranteed to be freed before handling the new one, or even a reload/reconnect will fail).
> Okay, so we need a button there?
That would be best, yes. We could also automatically reconnect when the tab/app gets focus again, but that may be too confusing.
> It's more like browsers per user, yes. Do you have other ideas how to approach this?
If link-sharing is the primary concern, we could also have an additional shared secret per browser (we already have `client_id`, the app could just send both). That way we can keep the "one connection is subscribed to one room/channel" assumption.

Against what level of technical proficiency are we protecting? Right now the stream urls are not authenticated / rate limited, are they?
To protect against everyone as tech-savvy as "can open the devtools and find stuff" seems like a boatton of work. "Can copypaste the site url" is probably good enough for now?

**Comment by raphaelm** [comment]
> Ah, okay. My gut tells me that a limit of one seems prone to race conditions (old connection must be guaranteed to be freed before handling the new one, or even a reload/reconnect will fail).

Not sure how you mean that or if this is a misunderstanding, but the backend currently (in this PR) works this way: If you connect, the system checks if there are too many open connections with the new one, then sends old connections a "replaced" message, but opens up the new one for you immediately. If this goes wrong due to a race condition or otherwise, the failure mode is allowing too many connections, not locking a user out.

> That would be best, yes. We could also automatically reconnect when the tab/app gets focus again, but that may be too confusing.

:+1:

> If link-sharing is the primary concern, we could also have an additional shared secret per browser (we already have client_id, the app could just send both). That way we can keep the "one connection is subscribed to one room/channel" assumption.
> Against what level of technical proficiency are we protecting? Right now the stream urls are not authenticated / rate limited, are they?

The stream urls are currently not authenticated right now, correct, but e.g. mux.com will theoretically support this soon, and it also would be possible to protect them if we wanted.

> To protect against everyone as tech-savvy as "can open the devtools and find stuff" seems like a boatton of work. "Can copypaste the site url" is probably good enough for now?

Probably yes. I think the current design is much simpler, and I don't think people will need to open too many tabs if we geed our UI right (e.g. two tabs, or tab + smartphone should be fine for most people), but we can do it via max. number of client IDs connected at the same time as well. Will need to work in the same way, though, since I guess we only want to limit _concurrent_ browsers per user, not browsers ever used.

**Comment by rashfael** [comment]
> Not sure how you mean that or if this is a misunderstanding, but the backend currently (in this PR) works this way: If you connect, the system checks if there are too many open connections with the new one, then sends old connections a "replaced" message, but opens up the new one for you immediately. If this goes wrong due to a race condition or otherwise, the failure mode is allowing too many connections, not locking a user out.

I think I confused myself there. Closing the old connections and always allow the newest one(s) like the current implementation is the best.

So, going forward, let's add some sort of "Reconnect" button, perhaps send the `connection_limit` together with the error to tell the user the limit? Should be good enough for "don't share logins". Support for multiple tabs is nice to have, but we probably have more important things to do?

**Comment by raphaelm** [comment]
Added a button, rebased, added i18n. Showing the user the limit would probably be user-friendly but not organizer-friendly, since "yeah, you shouldn't share it with friends but you can share it with three friends" isn't something you want to plainly tell the user, even if they could figure it out themselves. I'll merge this for now since it works and I think there are no big open design questions, we can still iterate on the details, but we can answer yes to the question if we can prevent abuse :)

**Pull request merged**
