### PR TITLE
Chat: allow to send pictures and other files

### LINKED ISSUE #150: Chat: allow to send pictures (and maybe other files)
I didn't find an issue for this, but it looks like it is already planned, since [feature-exploration.md](https://github.com/venueless/venueless/blob/dev/docs/feature-exploration.md) mentions file sharing.

### PR DESCRIPTION
**Pull request by johan12345**
A simple implementation for a "send image" button in chat rooms.
Pictures are uploaded using the existing upload mechanism (like for avatars) and displayed in the chat.

At the moment, it does not limit the size of uploaded pictures (as far as I know), or resize them in the browser like for avatars. That could probably still be implemented.

fixes #150

### CODE REVIEW

**Comment by rashfael** [comment]
Not sure if a single image message type is the right way. Multiple images in one messages with optional comments are also possible. The message format should probably be generalized to file uploads (with mime types). I'd also like to see some preview before sending and perhaps an upload progress indicator.
And yes, we'll need some server side image resizing sometime in the future.

**Comment by johan12345** [comment]
I have adapted it so that the messages now support multiple arbitrary files as well as an optional text body. The format looks like this:

```json
[
   "chat.event",
   {
      "event_id":56,
      "channel":"e5dd89de-4c54-4c7b-8da6-234114295653",
      "sender":"3c9ffd42-7608-4df3-a159-f337a3559c1c",
      "timestamp":"2020-10-18T21:27:35.067086+00:00",
      "event_type":"channel.message",
      "content":{
         "type":"files",
         "files":[
            {
               "url":"http://localhost:8375/media/pub/sample/c454e585-feb0-4f68-ba66-cc69c3edb052.yv3piBdVlm1K.pdf",
               "mimeType":"application/pdf",
               "name":"test.pdf"
            },
            {
               "url":"http://localhost:8375/media/pub/sample/9357c090-5e99-4589-88ce-9c83431b90d1.LhsLUJFaXXsp.png",
               "mimeType":"image/png",
               "name":"test1.png"
            },
            {
               "url":"http://localhost:8375/media/pub/sample/177b2e65-95fd-4d3a-93ea-085301caf69e.nWFxh5tCysZb.jpg",
               "mimeType":"image/jpeg",
               "name":"test2.jpg"
            }
         ]
      },
      "edited":null,
      "replaces":null
   }
]
```

**Comment by johan12345** [comment]
In the meantime, I have added:
- a preview of the files to be sent, with the possibility to cancel
image
- handling of upload errors (e.g. if file size > 10 MB) in the UI:
image
- a progress indicator
image
- possibility in the UI to send text together with the files
- possibility to add additional files after uploading the first batch

**Comment by rashfael** [comment]
[Review chat image uploads](https://trello.com/c/Mu8asa2C/1-review-chat-image-uploads)

**Comment by rashfael** [comment]
Looks like "edit message" does not work when the message has a file attached.

**Comment by rashfael** [comment]
Also it seems like deleting a preview item removes the last item instead?

**Pull request merged**
