### PR TITLE
Hybrid events

### PR DESCRIPTION
**Pull request by rashfael**
This PR implements the first batch of features from #304, mainly disabling stream autoplay and optimizing layout when autoplay is disabled to leave more space for chat on mobile.

If an event is hybrid or not can be controlled in the admin config, currently behind the `hybrid-event` feature flag:

Enabling hybrid mode in the config will allow users to disable autoplay per device in their preferences:

On mobile, the stream will now additially collapse to make space for more chat and other tools. The direction of the reactions cloud changes from bottom->top to right->left:

https://user-images.githubusercontent.com/1093590/147889230-e4b8df40-d92f-4574-a868-f4492dac7928.mp4

UI texts will certainly change in the future.

## Open Questions

- What about setting some form of "physical" vs "virtual" ticket mode inside the token? Do we have an upcoming use case for that?

### CODE REVIEW

**Comment by rashfael** [comment]
As discussed in our meeting, we'll make the autoplay setting available for everyone right now and defer more hybrid features to a later date.

**Comment by saschafoerster** [comment]
@rashfael @rashfael Another idea: How about a switch, that all mobile devices don't have outplay. That would mean, that people in the room with a mobile device just see the chat, remote people with mobile device need a click to play (which is nice anyway, if they have limited data plans) and all desktops have regular livestream autostarts?

**Comment by rashfael** [comment]
Disabling autoplay for for mobile devices is something to think about, but I would make that a general rule that mobile devices have autoplay disabled by default. No need to have settings for everything that impacts UX.
The biggest question is probably how to reliably detect "mobile", as always, since big tablets and non-full screen desktop browsers are not easily distinguishable.

**Comment by saschafoerster** [comment]
I think about smartphone users at the location especially, where there is a risk that the wifi bandwidth might be a bottleneck. So for hybrid events in general I think it's better to need one more click to play the videos instead of having a wifi, that doesn't work anymore. So I would prefer to have a larger list of devices without autoplay (without knowing too much about how to differentiate them). Even though I think in the mobile usage at the location itself in presence, there won't be to many tablet users either.

**Pull request closed without merging**
