### PR TITLE
Improve schedule

### PR DESCRIPTION
**Pull request by rashfael**
Uses same codebase as https://github.com/pretalx/schedule .
Introduces simple favving of sessions.
More features to come.

## Open Questions
- Should we save favs on the server for favs to work cross-device?

### CODE REVIEW

**Comment by rixx** [comment]
Saving favs on the server sounds good, but perhaps in a second step? I'd like to introduce an (anonymous) fav-saving feature to pretalx, too, so we should discuss if we want to provide similar, compatible APIs for both, or if we want a websocket API for venueless and an HTTP API for pretalx, etc.

**Comment by rashfael** [comment]
ref #305

**Comment by rashfael** [comment]
ref #137 #104

**Comment by rashfael** [comment]
As discussed in our meeting, we'll implement fav saving via venueless websocket, keeping the same payload pretalx will use with load/save calls of all favs.

**Pull request merged**
